### ISSUE TITLE
knownExtensions is missing negative variants

### ISSUE THREAD

**Issue by mvdan** [mvdan/hint#10]
See https://github.com/gelisam/hawk/issues/157. This also broke backwards compatibility in 0.5.0.

**Comment by mvdan** [comment]
@gelisam @jcpetruzza care to take a look at the fix above? @gelisam mentioned that some of the extensions (either positive or negative) didn't work on 7.10, so I'm not 100% sure on this.

**Comment by gelisam** [comment]
I confirm that this fix resolves gelisam/hawk#157.

You included `NoSafe`, `NoTrustworthy` and `NoUnsafe`, which don't make much sense, but since this is generated by a script it's probably easier to include them than to not include them, and I don't think including them will cause problems to anyone.

**Comment by mvdan** [comment]
Agreed. Thanks for confirming!
