### ISSUE TITLE
Binaries still depend on GHC being installed

### ISSUE THREAD

**Issue by mvdan** [mvdan/hint#3]
One of the biggest points of this library is that it lets you work around GHC having to be installed on the user's machine.

This seems to work as all the GHC modules are statically linked. But in practice, if you try to run the example program on a system without GHC, the following occurs:

```sh
 $ ./example
example: /usr/lib/ghc-7.10.3/settings: openFile: does not exist (No such file or directory)
```

We can confirm that the system does indeed have all dynamic libraries available, so it's not a linking issue:

```
 $ ldd example
        linux-vdso.so.1 (0x00007ffdd1391000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f4dd8317000)
        libutil.so.1 => /usr/lib/libutil.so.1 (0x00007f4dd8114000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f4dd7f10000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f4dd7cf3000)
        libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007f4dd7a7b000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f4dd7776000)
        libffi.so.6 => /usr/lib/libffi.so.6 (0x00007f4dd756d000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f4dd71cc000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4dd851f000)
```

**Comment by mvdan** [comment]
Which begs the question - why on earth is `/usr/lib/ghc-7.10.3` hard-coded into the binary?

**Comment by mvdan** [comment]
Looks like the culprit is `runGhcT`, which calls `initGhcMonad`:

https://github.com/ghc/ghc/blob/a84c21ebaa5c56a222d69f245ef4daa77054fdcb/compiler/main/GHC.hs#L460

This, in turn, calls `initSysTools`:

https://github.com/ghc/ghc/blob/a84c21ebaa5c56a222d69f245ef4daa77054fdcb/compiler/main/GHC.hs#L496

Which then does the unwanted `settings` file read:

https://github.com/ghc/ghc/blob/bb5afd3c274011c5ea302210b4c290ec1f83209c/compiler/main/SysTools.hs#L195

**Comment by jcpetruzza** [comment]
This is something interesting to improve, but keep in mind that there is probably no "easy" solution.

The thing is: ghc (the compiler and the library) needs to know where its global (think "default") packages are installed. This includes things such as base, transformers, etc. I don't think you can circumvent this: when the ghc api is initialized, it needs a path with the location of the package library. The way this is solved in hint is by using the ghc-paths package: the trick is that when ghc-paths is installed in your system (say, by cabal) it queries the ghc binary used to build it to find out where the global package library is, and records that. So then, whenever you depend on the ghc-paths, you get this for free. That is the hardcoded path you are seeing in your binary.

The problem is that, as you note, this doesn't work well for distributing binary versions of your program. IIRC, newer versions of ghc allow you to override the location of the global package lib using an environment variable, but still it would be cleaner to have an option in hint to pass around the desired location.

Still, this solves only half of the issue: you will still need to somehow ship all the packages you need along with your binary, and ensure they are "relocatable"(by default, cabal will make the packages it generates have absolute paths to its parts). In my opinion, this might be better to handle it in a complementary library/tool (not hint itself), since it is something orthogonal.

**Comment by gelisam** [comment]
>  ghc (the compiler and the library) needs to know where its global (think "default") packages are installed. This includes things such as base, transformers, etc. I don't think you can circumvent this: when the ghc api is initialized, it needs a path with the location of the package library.

I don't understand why those default packages need to be handled differently from other packages. A Haskell program which uses functions from base and transformers can run on a machine which doesn't have base and transformers to be installed, so it can't just be because the ghc library is implemented in terms of them. Rather, if the libraries need to be found at runtime, it must be because the ghc library needs them to understand the code it's interpreting. If that's an ordinary library like gloss, I can use `--package-db` to tell the ghc library where to look for a local copy of this library, and everything will be fine. Why can't ghc also look for the global libraries in that same package database?

**Comment by jcpetruzza** [comment]
I didn't mean to say that they need to be handled differently or that they are special in any way; just that some package db needs to be provided.

**Comment by mvdan** [comment]
So there is consensus that we should be able to provide hint with a package DB at runtime, instead of hard-coding a path at compile time. Any ideas how to accomplish this?

**Comment by jcpetruzza** [comment]
I would say "in addition to" instead of "instead of".

**Comment by mvdan** [comment]
Yep, that's what I meant to say :) Perhaps using the compile path by default and optionally a path given at runtime would work.

**Comment by mvdan** [comment]
What about environment variables? Like `GOPATH` in Go - we could have the library read them and use them if their values are non-empty.

This would work for executables. As far as using `hint` as a library, I don't know if being able to give it a path directly would be useful. It would be required for binaries to be able to take flags for these paths, for example.

**Comment by gelisam** [comment]
I don't think using an environment variable for this is a good idea. Environment variables are good for user-specific settings which each user puts in their `.bashrc`, it implies a user who knows what they're doing. But if the use case here is allowing the deployment of hint-based Haskell programs without having to ask the user to install GHC, it's not such a great improvement if we now have to ask the user to install the core Haskell libraries instead.

In such a deployment, the entity which knows where the core libraries are installed is not the user, but the program which uses hint. It probably deployed with its own copy of the core libraries and the libraries it wants interpreted expressions to use. And it's much easier and more natural for such a program to tell hint about the location of those libraries by calling a hint function than by setting an environment variable.

How about a function like [`searchPath`](https://hackage.haskell.org/package/hint-0.5.1/docs/Language-Haskell-Interpreter.html#v:searchPath)? Maybe `coreLibrariesPath`?

While we're at it, it would be nice to add something like `packageDatabasePath`, it would be a better API than [my current approach](https://github.com/gelisam/hawk/blob/master/src/System/Console/Hawk/Sandbox.hs#L118) of calling `unsafeRunInterpreterWithArgs` with "-package-db".

**Comment by lukexi** [comment]
It can definitely be done since @mchakravarty has pulled it off beautifully in [Haskell For Mac](http://haskellformac.com/)! I'm right in the midst of solving this myself, so I can easily package and distribute a VR Haskell programming environment I'm working on. I run code via [Halive](https://github.com/lukexi/halive), but it's very similar to Hint. So it would be excellent to figure out what's needed. I'll let you know what I find... 

Any hints Manuel? :wink: :two_hearts:

**Comment by mchakravarty** [comment]
The `settings` file isn't the real problem. It is just the first thing GHC stumbles over during initialisation. The general issue is that GHC requires its *library directory* (`libdir`) — the directory printed by `ghc --print-libdir`. This directory contains a range of important files, including `settings` and the package database (that is the meta data as well as all the `hi` and object files).

As somebody already mentioned, the library directory is the directory passed to `runGhc` or `runGhcT` (and ultimately needed by `initGhcMonad`, which initialises a GHC session). To distribute binaries including the GHC interpreter raises two challenges:

1. You need to locate the library directory (that is usually not hard).
2. You may need to re-locate the library directory (that one is more tricky).

At least on OS X (e.g., for [Haskell for Mac](http://haskellformac.com/)), the second point is crucial as Mac users expect to be able to put applications anywhere on their filesystems (i.e., you cannot expect a fixed location for the application or any of its resources during runtime). On Linux, where software is usually installed by package managers, the second point is less of a concern as applications tend to be installed at fixed locations.

My solution for these issues in [Haskell for Mac](http://haskellformac.com/) are as follows:

1. Mac applications are distributed as [Bundles](https://developer.apple.com/library/mac/documentation/CoreFoundation/Conceptual/CFBundles/Introduction/Introduction.html). I build GHC in the form of an [embedded framework bundle](https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html) — this is mostly along the lines of the original OS X installer distribution that I contributed to GHC many years ago. Cocoa provides methods to locate the main app bundle and embedded bundles via the [NSBundle](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSBundle_Class/index.html) class. I use those methods before invoking `runGhc` to obtain the path.
2. To relocate the resources in the library directory (and in particular rewrite all absolute paths in the package configuration files), I wrote a small helper tool. It is invoked by the main Haskell for Mac app during initialisation (and before GHC is spun up). It also gets the library path as described above and then rewrites all package conf files and whatever needs changing and then recreates the binary package database using the embedded version of `ghc-pkg`.

On OS X, re-location gets complicated further due to sandboxing and code signing (which is absolutely required for apps to be distributed through the Mac App Store like Haskell for Mac, but also affecting directly distributed apps as the distribution of unsigned apps raises many alarm bells on recent versions of OS X by way of [Gatekeeper](https://support.apple.com/en-us/HT202491)).

A properly code signed app is immutable (which should make every Haskell programmer happy 😉) — i.e., the relocation process cannot alter the embedded framework. However, every sandboxed app has got a so-called [app container](https://developer.apple.com/library/mac/documentation/Security/Conceptual/AppSandboxDesignGuide/MigratingALegacyApp/MigratingAnAppToASandbox.html) where all of its mutable data is located. My GHC relocation helper creates a copy of the library directory in the app container, properly relocated for that location. It is also smart enough to re-create that copy only if things changed (and not generally on every launch of Haskell for Mac).

That's basically it. There is one more kink, though. You need to make sure that all dynamic libraries are relocatable, too. The standard GHC build is creating a rather naive (i.e., Linux-style) set up on OS X. Currently, I am solving that in a rather clunky manner using `install_name_tool` to rewrite all library names and RPATHs to use relative addressing based on `@loader_path`.

I hope this helps.

**Comment by gelisam** [comment]
Wow, and I thought the Linux situation was complicated! I see that OS X has the same problems, and then some.

So I was worried about the achievability of the end goal of installing hint programs without installing GHC, because the folder in which the settings file is located happens to contain the GHC executable and 450 Mb of extra stuff. So yesterday I've created a [proof of concept](https://github.com/gelisam/deploy-hint) in which I create one docker container with GHC installed and one docker container without, and then I try to copy just enough files between the two systems to make a tiny hint program run successfully.

The good news is that we do not need the GHC executable nor most of those 450 Mb of stuff, we only need the folders of the core libraries which our application actually uses and their configuration files in the global package database. We also need C libraries such as `libgmp.so`.

The bad news is that even though GHC doesn't need to be installed, GCC does. I haven't looked at what it would take to package GCC along with the deployed program in the same way I'm deploying libgmp and the core Haskell libraries along with my test program.

So far my proof of concept can evaluate Haskell expressions which only depend on modules from the core libraries, and the C libraries can be deployed next to the test program. I'm currently working on extending my proof of concept to support modules from hackage, and on allowing the global and local package databases to also be located next to the test program instead of at the same absolute path as on the original machine. It turns out that the package database uses absolute paths, but it's a text file so it shouldn't be too hard for the deployed program to rewrite those paths before running hint. After rewriting those paths though, we need to run ghc-pkg to regenerate the cache file, so at least that part of GHC will need to be installed.

**Comment by mchakravarty** [comment]
@gelisam It doesn't actually need GCC. There is one call to GCC using the `--print-file-name` option. You can handle this by replacing GCC by a simple shell script handling this particular case.

**Comment by gelisam** [comment]
Thanks! My proof of concept is now much improved thanks to you. I've also done all the improvements I mentioned in my previous comment, and the last hurdle is getting ghc-pkg to run on the target machine.

**Comment by mchakravarty** [comment]
I am glad to hear that my comments prove helpful. As for `ghc-pkg`, the actual binary (located in the `bin/` directory of GHC library directory) is invoked through a shell script wrapper that gets the location of the package database via the `--global-package-db` option. You need to edit that script such that it passes the right location (and invokes the binary at the right location). If `ghc-pkg` is dynamically linked, you will also need to rewrite its dynamic libraries or set `LD_LIBRARY_PATH` in the shell script wrapper. (I am linking everything dynamically as it keeps the distribution smaller — and it is already pretty big.)

**Comment by mvdan** [comment]
Thanks everyone for your input! And nice work @gelisam with your proof of concept :)

Should any of the code in your proof of concept make it to `hint`? Or perhaps there is something that could be changed here to make the usage of the library in this way easier.

**Comment by gelisam** [comment]
The goal of my proof of concept is to demonstrate that yes, with enough work, it is possible to deploy a hint-based program on a machine which doesn't have ghc installed. Without such a proof of concept, I was afraid we might be wasting our time discussing details such as how hint should expose libdir to the application, without knowing if doing so would help with the end goal. Since my proof of concept was successful, I think we should resume that discussion.

I don't think there's any code from my proof of concept as currently implemented which deserves to be included inside hint. I modified hint in a quick and dirty way, by adding an extra parameter to `runInterpreter`. Since that breaks the existing API, I'd advise using a different method which uses ghc-paths by default and allows the path to be overridden by the application if needed.

The rest of my proof of concept illustrates which files need to be copied from one machine to the other, but it's doing so in a hardcoded deployment script rather than via some Haskell code which could be integrated into hint. I think it would be very useful to package the deployment strategy, in hint or elsewhere, but for now let's focus on the prerequisite: allowing the user the override the libdir.

**Comment by mvdan** [comment]
> I'd advise using a different method which uses ghc-paths by default and allows the path to be overridden by the application if needed.

How about a config option next to `languageExts`, `searchFilePath` et al - something like `librariesPath` defaulting to  `GHC.Paths.libdir`.

**Comment by mvdan** [comment]
Bump @gelisam, in case you missed the comment above :)

**Comment by gelisam** [comment]
+1

**Comment by mvdan** [comment]
@gelisam please take a look at the commit above. If you have a cleaner or better way to fix this, please let me know or just open a PR.

**Comment by gelisam** [comment]
Hmm, I wanted to modify my proof of concept to use that version, but it looks like the new `runInterpreterWithArgsLibdir` function is not exposed by the package?

**Comment by mvdan** [comment]
Ah, you're right! Will merge #9.

**Comment by mvdan** [comment]
Let me know if you're happy with the branch and I'll merge with master and close this issue.

**Comment by gelisam** [comment]
Yes, I am happy with the branch now :)

I've updated my proof-of-concept, the [latest version](https://github.com/gelisam/deploy-hint/tree/85918a527c8801f5b56f94897e6744c2cc86ee38) is using that branch and it works just fine.

**Comment by mvdan** [comment]
Merged.

**Comment by lukexi** [comment]
Just wanted to note this here for you all since it's relevant for Hint too! There are a couple new tweaks regarding libmingw32.a and libmingwex.a on Windows when doing relocatable GHC API-using executables.

https://phabricator.haskell.org/D1805#69336
