### ISSUE TITLE
How to narrow down source of `GhcException "Unable to use Data Parallel Haskell (DPH) ..."`?

### ISSUE THREAD

**Issue by Wizek** [mvdan/hint#46]
Any clue how I could narrow down this issue?

``` hs
Left (GhcException "Unable to use Data Parallel Haskell (DPH):

To use ParallelArrays, you must specify a DPH backend package
Look for packages named 'dph-lifted-*' with 'ghc-pkg'
You may need to install them with 'cabal install dph-examples'")
```

I'm getting to know hint at the moment, and this happened when I tried to load a module of a codebase I am working on. I'm guessing that one of the packages imported try to use DPH internally. Could I somehow get a clue which one might be the offender?

Also, does it make more sense to try to remove the dependency when I find it, or can perhaps `hint` deal with DPH if I try to provide it with the `dph-lifted-` libraries it mentions?

**Comment by mvdan** [comment]
I really don't know. Perhaps try using `ghc` or `ghci` first, as `hint` should just be a way to access their features. They might do a better job at giving you errors or suggestions.

**Comment by gelisam** [comment]
Another hint: if your code compiles when built with `cabal` but not `ghc`, it might be because `cabal` passes extra flags to `ghc`. Use `cabal`'s verbose mode to list those extra flags; but watch out, there will be a _lot_ of them, so you'll have to weed them out in order to find the important ones.

In particular, googling for [Data Parallel Haskell](https://wiki.haskell.org/GHC/Data_Parallel_Haskell), I found some documentation which says to give `ghc` the `-fdph-par` option to select a particular backend. First make sure you can figure out the command-line options to compile your code without `cabal`, with only `ghc`, then figure out the command-line options to do the same with `ghci`. Finally, you can then use [`unsafeRunInterpreterWithArgs`](https://hackage.haskell.org/package/hint-0.7.0/docs/Language-Haskell-Interpreter-Unsafe.html#v:unsafeRunInterpreterWithArgs) to give `hint` the command-line arguments you'd give `ghci`.

**Comment by Wizek** [comment]
Thanks for the pointers guys. It turns out quite likely this was the offender in my case:

```hs
set [languageExtensions := availableExtensions]
```

I still don't fully grasp how hint works, in my confusion I thought this made some extensions available for the interpreter. But it seems instead this is the list that specifies all the enabled extensions, and `{-# LANGUAGE #-}` and `{-# OPTIONS_GHC #-}` pragmas seem to be fully ignored.

But at least I can load my module now, so yay for that!
