### ISSUE TITLE
Seg Fault when returning Data type?

### ISSUE THREAD

**Issue by polygonhell** [mvdan/hint#5]
This could easilly be my fault, I have what appears to be a trivial test
example code here https://github.com/polygonhell/HintTest

On my Mac this segfaults when I cabal run (or just execute) it, but completes if I run main from inside the cabal repl.
On my Windows box it segfaults in both cases.

Since I could get basic types like Int to work correctly including functions on basic types, I assume the issue is the shared SomeType data definition. 
I couldn't find an example that demonstrated the use of more complex types.

**Comment by mvdan** [comment]
Confirming on linux/amd64:

```
Running HintTest...
["TestHint","SomeType"]
[Fun "test"]
[Data "SomeType" ["Ploop","Floop"]]
got something
zsh: segmentation fault (core dumped)  cabal run
```

**Comment by mvdan** [comment]
To be more precise:

```sh
 $ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.3
```

I'm not familiar with debugging segfaults in Haskell, so any help is welcome.

**Comment by polygonhell** [comment]
I ran the code in LLDB, and this is all I could get out of it, unfortunately I'm not familiar enough with the guts of GHC for it to provide any real insight.

It dies here, with a bad memory reference

`HintTest`s1bh_info:
    0x1000037b0 <+0>:  leaq   -0x10(%rbp), %rax
    0x1000037b4 <+4>:  cmpq   %r15, %rax
    0x1000037b7 <+7>:  jb     0x10000385e               ; c1cM_info + 46
    0x1000037bd <+13>: leaq   0x34(%rip), %rax          ; c1cG_info
    0x1000037c4 <+20>: movq   %rax, -0x10(%rbp)
    0x1000037c8 <+24>: movq   0x10(%rbx), %rax
    0x1000037cc <+28>: movq   0x18(%rbx), %rbx
    0x1000037d0 <+32>: movq   %rax, -0x8(%rbp)
    0x1000037d4 <+36>: addq   $-0x10, %rbp
    0x1000037d8 <+40>: testb  $0x7, %bl
    0x1000037db <+43>: jne    0x1000037f8               ; c1cG_info
->  0x1000037e1 <+49>: jmpq   *(%rbx)
    0x1000037e3 <+51>: nopl   (%rax,%rax)
    0x1000037e8 <+56>: addl   %eax, (%rax)
    0x1000037ea <+58>: addb   %al, (%rax)
    0x1000037ec <+60>: addb   %al, (%rax)
    0x1000037ee <+62>: addb   %al, (%rax)
    0x1000037f0 <+64>: andb   %al, (%rax)
    0x1000037f2 <+66>: addb   %al, (%rax)
    0x1000037f4 <+68>: addb   %al, (%rax)
    0x1000037f6 <+70>: addb   %al, (%rax)` 

The registers at this point are

`       rax = 0x000000010349f4b1  ghczmprim_GHCziTypes_ZMZN_closure + 1
       rbx = 0x0000010555e02800
       rcx = 0x0000000000000001
       rdx = 0x0000000105501700
       rdi = 0x0000000106982010
       rsi = 0x000000010555c380
       rbp = 0x00000001055fcf70
       rsp = 0x00007fff5fbfb7e8
        r8 = 0x0000000000000006
        r9 = 0x000000010555c678
       r10 = 0x000000010555c368
       r11 = 0x0000000106968700
       r12 = 0x000000010555c6a8
       r13 = 0x00000001034a0e18  HintTest`MainCapability + 24
       r14 = 0x0000000000000006
       r15 = 0x00000001055f50c0
       rip = 0x00000001000037e1  HintTest`s1bh_info + 49
    rflags = 0x0000000000010246
        cs = 0x000000000000002b
        fs = 0x0000000000000000
        gs = 0x0000000000000000`

It's dereferencing rbx @ 0x0000010555e02800 which is memory not mapped to the application.

this is called from the following callstack

`ghczmprim_GHCziTypes_ZMZN_closure
stg_upd_frame_info_dsp
`
All in all not a very useful stack trace.
My best guess is it's trying to dereference a thunk, and pulling out the wrong address to jump to. Could it be something like differing compiler options for the application and the Hint compiled code resulting in a different header for the closure or something?

**Comment by polygonhell** [comment]
Actually looking at it further, while 0x0000010555e02800 is not mapped, it looks like 0x000000010555e028, so possibly some sort of misaligned write?

**Comment by gelisam** [comment]
> This could easilly be my fault, I have what appears to be a trivial test example code here

Your code is not as trivial as it first appears: you have a dependency loop. If I was reimplementing your example code, I would have divided it into three layers:

1. package `some-type`, exposing `SomeType`
1. file `plugin/TestHint.hs`, depending on `some-type`
1. package `HintTest`, depending on `some-type` and `hint` at compile-time and on `plugin/TestHint.hs` at runtime

Note how each layer only depends on layers which come before it. By comparison, here are the logical dependencies of your code:

1. file `plugin/TestHint.hs`, depending on `hint-test`'s `SomeType`
1. package `HintTest`, exposing `SomeType`, depending on `hint` at compile-time and on `plugin/TestHint.hs` at runtime

Notice the loop. That's not what causing the problem though, because the way you've implemented it doesn't actually involve a loop. Instead, you have have references to two types which happen to have the same name but are actually different entities. Here's what I think is happening:

1. you compile `src/SomeType.hs` and `src/Main.hs` into an executable named `HintTest`. Within this codebase, there is a type called "SomeType", which I'll call "SomeType1". Since this is a program and not a library, nobody else can refer to `SomeType1` and the compiler is allowed to use any binary representation it wishes.
1. at runtime, you interpret files `plugin/TestHint.hs` and `src/SomeType.hs`. It just so happens that `src/SomeType.hs` contains the same code as the `src/SomeType.hs` which was used to compile the `HintTest` executable, but in Haskell types use nominal equality, not structural equality, so this coincidence is irrelevant. This is a new type which I'll call "SomeType2".
1. the line of code `interpret "test 5" (as :: SomeType)` becomes the runtime expression "test 5 :: SomeType". Note that since the type annotation `(as :: SomeType)` is part of the code of the `HintTest` executable, this first annotation says that the expression "test 5" is expected to have type `SomeType1`. By contrast, since the expression "test 5 :: SomeType" is evaluated at runtime, this second annotation says that the expression "test 5" has type `SomeType2`.
1. hint uses ghc to interpret "test 5 :: SomeType", and since ghc did not report any type error, hint assumes that "test 5" has the expected type, and so it unsafeCoerces the result to `SomeType1`. This is the bug.
1. Later on, the `HintTest` executable attempt to print a variable of type `SomeType1`, but the bits to which this variable points to actually has the shape of a `SomeType2`. Since one type is compiled and the other is interpreted, the bit patterns are very different, and so a segfault ensues.

**Comment by gelisam** [comment]
When you run `HintTest` in interpreted mode, the incorrect coercion still occurs, but since `SomeType1` and `SomeType2` are both interpreted (and are both defined by the same code), the bit patterns are the same and so no segfault occurs.

**Comment by polygonhell** [comment]
Yes thanks that makes sense.
I was assuming that the SomeType being added to the context would be the one from the host application rather than another copy. 
I assume then that there is no way to expose functionality from the host application to the compilation context without factoring the shared functionality out as a separate package?

**Comment by polygonhell** [comment]
Closing this as it's my bug, not Hints

**Comment by gelisam** [comment]
> I assume then that there is no way to expose functionality from the host application to the compilation context without factoring the shared functionality out as a separate package?

I was curious about this too, so I tried to implement the circular dependency I described earlier, and it worked fine! I sent you a pull request (which you already merged, you're fast!) to demonstrate how I did it.

If the functionality of the host application which you want to expose doesn't require new types, you can also expose it to the program executed by hint simply by passing that functionality as an argument. For example, suppose the host application implements `square :: Int -> Int` but does not expose it as a library. The plugin can still use `square` by expecting it as an argument:

    test :: (Int -> Int) -> Int -> SomeType
    test square x = Ploop (square x)

And then the host can pass its `square` implementation by asking hint to return a function and then passing arguments to that function:

    interpret "test" infer <*> pure square <*> pure (5 :: Int)

**Comment by polygonhell** [comment]
Yes, thanks for the example, it was only fast because I happened to look just after you checked in. 

It looks like the "magic" is exposing the the module and then not exposing it's source path to the Hint context.

I did get it working by factoring out the shared code, it was straight forwards once I realized that ghc couldn't see the modules installed to a sandbox unless it was explicitly added to the GHC_PACKAGE_PATH. unsafeRunInterpreterWithArgs is a much better way that I was using as well
```cabal exec cabal run```
was pretty ugly.

Cabal just isn't the best build system for working with dependent libraries, so I prefer this approach.

My original example actually returned a function, I only changed it to return the Type to to minimize complexity, my actual use case is more of the form
fn :: StateObject -> Args -> (ResultType, StateObject)
Which should be simple enough.
