### ISSUE TITLE
eval on Polymorphic Functions / Types

### ISSUE THREAD

**Issue by Aerate** [mvdan/hint#50]
I have a polymorphic function on lists that returns empty when given empty
```
foo :: [a] -> [a]
foo [] = []
foo [a,b] = ...
```
Evaluation of the function works as expected if nonempty, e.g.
```
...
eval "foo [1,2]"
...
```
but gives an error if the list is empty:
```
...
eval "foo []"

ERROR: Won't compile:
Ambiguous type variable ‘a0’ arising from a use of ‘show_M25906720550819198279345’
      prevents the constraint ‘(Show a0)’ from being solved.
      Probable fix: use a type annotation to specify what ‘a0’ should be.
```
Using `interpret` solves this, but then a type is needed (which I don't necessarily have knowledge of at runtime). Is this the intended behavior of `eval`, and if so, is there some easy way around this?

**Comment by mvdan** [comment]
Perhaps you could try using `unsafeInterpret`, which is what both `eval` and `interpret` build on top of.

Are you using `Hint` via `ghci`, or in a compiled binary? If you're only trying one, try the other too.

**Comment by gelisam** [comment]
The error message is correct: the type of `foo []` _is_ ambiguous. I'll be using `id` instead of `foo`, but the idea is the same.

What is the type of `id []`?

    > :t id []
    id [] :: [a]

`eval` uses `show` and `read` to serialize the value from the code which is running inside the interpreter and move it out to the code which is running outside the interpreter. In order to do that, we need a concrete type so we can use its `Show` instance; a polymorphic type such as `[a]` won't do.

If you type `id []` is ghci, you'll get this:

    $ id []
    <interactive>: warning: [-Wtype-defaults]
        • Defaulting the following constraint to type ‘()’
            Show a0 arising from a use of ‘print’
        • In a stmt of an interactive GHCi command: print it
    []

That is, ghci _is_ able to `show` the result of `id []` despite its ambiguous type, but it does so by defaulting the ambiguous type `a` to the type `()`. Looking at the [documentation of type defaulting](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/ghci.html#type-defaulting-in-ghci), we can see that defaulting to `()` uses the `ExtendedDefaultRules` extension, which is apparently on by default in ghci. It is not on by default in hint, but you can turn it on manually:

    > :{
    runInterpreter $ do
      set [languageExtensions := [ExtendedDefaultRules]]
      setImports ["Prelude"]
      eval "id []"
    :}
    Right "[]"

**Comment by Aerate** [comment]
Thank you @gelisam, this should work perfectly for my case. :)
