### ISSUE TITLE
Configurable signal handling in the interpreter thread

### ISSUE THREAD

**Issue by yaxu** [mvdan/hint#51]
I'm having problems with handling ctrl-c (SIGINT) with Hint - my interpreter thread stops working. I spotted this in the documentation for `runInterpreter`

```
NB. The underlying ghc will overwrite certain signal handlers
(SIGINT, SIGHUP, SIGTERM, SIGQUIT on Posix systems, Ctrl-C handler on Windows).
In future versions of hint, this might be controlled by the user.
```

I'm using this for a music performance tonight, and it's a bit of a problem if everything stops working on ctrl-c. Is there a way of getting hint to ignore SIGINT?

**Comment by mvdan** [comment]
You're using a Haskell interpreter to play music?

My knowledge of signal handling in Haskell is non-existent, I'm afraid. Happy to review and merge a patch to make this configurable, though.

**Comment by gelisam** [comment]
In Haskell, the default behaviour of `ctrl-c` is to send the [`UserInterrupt`](https://hackage.haskell.org/package/base-4.10.1.0/docs/Control-Exception.html#v:UserInterrupt) exception to the main thread. It is possible to observe this behaviour by catching the exception before it causes the program to terminate:

    import Control.Concurrent
    import Control.Exception

    sleepVerbosely :: String -> IO ()
    sleepVerbosely threadName = do
      r <- try $ do
        putStrLn $ threadName ++ " sleeps for 5 seconds..."
        threadDelay 5000000
      putStrLn ""
      case r :: Either SomeException () of
        Left _ -> putStrLn $ threadName ++ " was interrupted by an exception"
        Right () -> putStrLn $ threadName ++ " slept for 5 seconds"

    -- > main
    -- main sleeps for 5 seconds...
    -- ^C
    -- main was interrupted by an exception
    main :: IO ()
    main = sleepVerbosely "main"

Catching the exception allows the program to stay alive despite the user's wishes, so by default, if the user types `ctrl-c` a second time, it abruptly terminate the program without using the exception mechanism:

    -- > main
    -- main sleeps for 5 seconds...
    -- ^C
    -- main was interrupted by an exception
    -- main again sleeps for 5 seconds...
    -- ^C
    main :: IO ()
    main = do
      sleepVerbosely "main"
      sleepVerbosely "main again"

There are [reports](http://neilmitchell.blogspot.ca/2015/05/handling-control-c-in-haskell.html) that it's the shell which does this, not the default interrupt handler, but I get the same result if I use [`raiseSignal`](https://hackage.haskell.org/package/unix-2.7.2.2/docs/System-Posix-Signals.html#v:raiseSignal) twice instead of typing ctrl-c twice, so it does look like this is the work of the default handler. Especially since, as you point out, we can make both hitting ctrl-c and hitting ctrl-c twice do nothing by setting the interrupt handler to `Ignore`:

    import System.Posix.Signals

    -- > main
    -- main sleeps for 5 seconds...
    -- ^C
    -- main slept for 5 seconds
    -- main again sleeps for 5 seconds...
    -- ^C
    -- main again slept for 5 seconds
    main :: IO ()
    main = do
      _ <- installHandler sigINT Ignore Nothing
      sleepVerbosely "main"
      sleepVerbosely "main again"

Instead of `Ignore`, we can also install our own interrupt handler. For example, if we type an expression which takes too long to compute in ghci, we can use ctrl-c to interrupt it and go back to the ghci prompt. And from there, if we type another slow expression, we would like to be able interrupt it again, we don't want ctrl-c to terminate the entire ghci session!

    handleCtrlC :: IO ()
    handleCtrlC = do
      childThreadId <- myThreadId
      let interruptChild :: IO ()
          interruptChild = throwTo childThreadId UserInterrupt
      _ <- installHandler sigINT (Catch interruptChild) Nothing
      pure ()

    -- > main
    -- main sleeps for 5 seconds...
    -- ^C
    -- main was interrupted by an exception
    -- main again sleeps for 5 seconds...
    -- ^C
    -- main again was interrupted by an exception
    main :: IO ()
    main = do
      handleCtrlC
      sleepVerbosely "main"
      sleepVerbosely "main again"

`hint` [uses `runGhcT`](https://github.com/mvdan/hint/blob/c6fdd3c272af1df6d5293c03c59e79b8877bec21/src/Hint/InterpreterT.hs#L45), which [calls `withSignalHandlers `](https://github.com/ghc/ghc/blob/59fa7b32b018a91f81773ca676251a0b2761ef56/compiler/main/GHC.hs#L461), which does [basically the same thing](https://github.com/ghc/ghc/blob/7446c7f68bd5addd2f2db0d8d5910fb963869c47/compiler/utils/Panic.hs#L239-L251) as my `handleCtrlC`. That's what the comment about how "the underlying ghc will overwrite certain signal handlers" means.

----

Now, you mentioned that your interpreter _thread_ stopped working. By default, child threads are not sent any exception when ctrl-c is pressed:

    -- > main
    -- child sleeps for 5 seconds...
    -- main sleeps for 5 seconds...
    -- ^C
    -- main was interrupted by an exception
    -- main again sleeps for 5 seconds...
    -- child slept for 5 seconds
    -- main again slept for 5 seconds
    main :: IO ()
    main = do
      _ <- forkIO $ do
        sleepVerbosely "child"
      threadDelay 1000000
      sleepVerbosely "main"
      sleepVerbosely "main again"

But what if we did want the exception to be thrown to the child thread instead of to the main thread? We can achieve this by overwriting the interrupt handler:

    -- > main
    -- child sleeps for 5 seconds...
    -- main sleeps for 5 seconds...
    -- ^C
    -- child was interrupted by an exception
    -- main slept for 5 seconds
    main :: IO ()
    main = do
      _ <- forkIO $ do
        handleCtrlC
        sleepVerbosely "child"
      threadDelay 1000000
      sleepVerbosely "main"

In your case, you are attempting to disable ctrl-c by setting the interrupt handler to `Ignore`, but then you spawn an "interpreter thread" which overwrites this `Ignore` by setting up its own interrupt handler:

    -- > main
    -- child sleeps for 5 seconds...
    -- main sleeps for 5 seconds...
    -- ^C
    -- child was interrupted by an exception
    -- main slept for 5 seconds
    main :: IO ()
    main = do
      _ <- installHandler sigINT Ignore Nothing
      _ <- forkIO $ do
        handleCtrlC
        sleepVerbosely "child"
      threadDelay 1000000
      sleepVerbosely "main"

@yaxu, that's the behaviour you see, right? You set the interrupt handler to `Ignore`, and your main thread is unaffected by ctrl-c, but the child thread still dies. However, the reason the main thread is unaffected by ctrl-c is not because you set the interrupt handler to `Ignore`, it's because the child thread overwrites the ctrl-c handler.

With `hint` as currently written, there is no way for you to prevent `hint` from overwriting the interrupt handler. But there is an easy workaround: you can overwrite it again!

    -- > main
    -- child sleeps for 5 seconds...
    -- main sleeps for 5 seconds...
    -- ^C
    -- child slept for 5 seconds
    -- main slept for 5 seconds
    main :: IO ()
    main = do
      _ <- installHandler sigINT Ignore Nothing
      _ <- forkIO $ do
        handleCtrlC
        _ <- installHandler sigINT Ignore Nothing
        sleepVerbosely "child"
      threadDelay 1000000
      sleepVerbosely "main"

This workaround seems to work fine in this toy model of the problem, let's now make sure it also works with the real `hint`. First, let's make sure we can reproduce the problem:

    interpretVerbosely :: IO () -> IO ()
    interpretVerbosely body = do
      r <- runInterpreter $ do
        liftIO body
      putStrLn ""
      case r :: Either InterpreterError () of
        Left e -> putStrLn $ "interpreter failed with: " ++ show e
        Right () -> putStrLn $ "interpreter succeeded"

    -- > main
    -- child sleeps for 5 seconds...
    -- main sleeps for 5 seconds...
    -- ^C
    -- child was interrupted by an exception
    -- interpreter succeeded
    -- main slept for 5 seconds
    main :: IO ()
    main = do
      _ <- installHandler sigINT Ignore Nothing
      _ <- forkIO $ interpretVerbosely $ do
        sleepVerbosely "child"
      threadDelay 1000000
      sleepVerbosely "main"

And finally, let's confirm that the workaround works with the real `hint`:

    -- > main
    -- child sleeps for 5 seconds...
    -- main sleeps for 5 seconds...
    -- ^C
    -- child slept for 5 seconds
    -- interpreter succeeded
    -- main slept for 5 seconds
    main :: IO ()
    main = do
      _ <- installHandler sigINT Ignore Nothing
      _ <- forkIO $ interpretVerbosely $ do
        _ <- installHandler sigINT Ignore Nothing
        sleepVerbosely "child"
      threadDelay 1000000
      sleepVerbosely "main"

Success!

-----

For ghci, it makes a lot of sense to allow the user to interrupt the computation with ctrl-c. But for `hint`, we don't know whether the caller is using `hint` to implement a repl or something else. And if they are implementing a repl, installing this interrupt handler by default is not sufficient: they will also have to catch the `UserInterrupt` exception and restore their `repl`'s prompt. So I think the default behaviour of `runInterpreter` should be to _not_ mess with the interrupt handler, and then we could expose a repl-friendly wrapper which would attach the interrupt handler, catch the `UserInterrupt` and return an `Either`. What do you think, @mvdan ?

**Comment by yaxu** [comment]
Thanks very much @gelisam, quite possibly the clearest and most thorough response I've had to a technical question! This does explain the behaviour I've been seeing very well. Thanks very much for the workaround!

**Comment by mvdan** [comment]
@gelisam I agree that we shouldn't mess with the interrupt handler by default. Feel free to send a patch :)
