### ISSUE TITLE
runInterpreter hangs on ghci

### ISSUE THREAD

**Issue by JulianLeviston** [mvdan/hint#57]
From the docs:

> NB. The underlying ghc will overwrite certain signal handlers (SIGINT, SIGHUP, SIGTERM, SIGQUIT on Posix systems, Ctrl-C handler on Windows). In future versions of hint, this might be controlled by the user

Is there any chance this might be adjusted sometime soon? Or is there possibly some work I could help out with here? Running in ghci to test means my session gets frozen when it runs `runInterpreter`.

**Comment by mvdan** [comment]
See #51 - a pull request is already being worked on. The fix should come out with 0.8.0 in a few weeks.

**Comment by JulianLeviston** [comment]
Oh wow, so awesome! Thankyou!

**Comment by gelisam** [comment]
> Running in ghci to test means my session gets frozen when it runs `runInterpreter`.

What do you mean? Can you give repro steps? On my computer, `runInterpreter` works just fine in `ghci`:

    > import Language.Haskell.Interpreter
    > runInterpreter $ setImportsQ [("Prelude", Nothing)] >> eval "2+2"
    Right "4"

And interrupting it with Ctrl-C works fine too:

    > runInterpreter $ setImportsQ [("Prelude", Nothing)] >> eval "length [0..]"
    Right "
    ^C
    Interrupted.

> From the docs:
> 
>> NB. The underlying ghc will overwrite certain signal handlers (SIGINT, SIGHUP, SIGTERM, SIGQUIT on >> Posix systems, Ctrl-C handler on Windows). In future versions of hint, this might be controlled by the user
> 
> Is there any chance this might be adjusted sometime soon? 

So, to clarify: on your computer, you're doing something with `runInterpreter` in `ghci` which causes it to become unresponsive, and Ctrl-C does not kill it. You have read the above paragraph, and you have concluded that while `ghci` normally interprets Ctrl-C as "abort the current expression", hint replaces the Ctrl-C signal handler with a handler which ignores the Ctrl-C, thereby explaining why Ctrl-C does not kill your interpreter.

If that was the case, then the fact that I already wrote a patch which stops hint from replacing those signal handlers would be great news. Unfortunately, signal handlers are definitely not the problem here.

One reason is that hint was _only_ replacing the signal handlers when it was the top-level invocation of the ghc library; in ghci, hint's invocation is nested inside ghci's invocation, and so the signal handlers are _not_ replaced, and the signal-replacing code cannot explain the behaviour you are seeing.

Furthermore, even when the signal-replacing code does get triggered, hint does _not_ replace the Ctrl-C signal handler with one which ignores Ctrl-C, but with one which interrupts the current expression, just like `ghci`. This was useful for implementing `ghci`-like interpreters, but in #51 a user had a use case which was not a `ghci`-like interpreter, and for that use case they wanted Ctrl-C to be ignored. This is why we are removing the code which overwrites the signal handlers. Since the signal-replacing code is replacing the Ctrl-C handler with a handler which _does_ interrupt the interpreter when Ctrl-C is pressed, the signal-replacing code cannot explain why your interpreter does not get interrupted.

So, it looks like you have encountered a brand new bug, which has nothing to do with #51. Could you tell us more about the behaviour you are seeing?

**Comment by JulianLeviston** [comment]
Okay... this only happens when I'm running some kind of TCP/IP server so far.

Once it happened when I was running `runInterpreter` inside of a Snap application in GHCi (ie my `main` function at the cmd line, and more recently it's happened because I built a TCP server with tcp simple and if that server hits `runInterpreter` (it can do various things depending on what requests it gets), then it hangs.

When I say it hangs, CTRL-C no longer works... the server still works and everything's good, but that session is effectively locked out in terms of being able to quit back to the prompt. If I want to close it, I have to find the PID and `ps kill` it.

I'm not 100% sure it's a brand new bug, but hopefully you can reproduce the use-case relatively easily. If not, there's the frame of the snap app I was doing it in at https://github.com/GetContented/substance — but that doesn't include hint (that was done as local experimentation on my local machine only) — one could quickly include hint and put a runInterpreter expression in one of the routes, though, I'd imagine.

H2H, and thanks for noticing that this was the case (if it is).

**Comment by gelisam** [comment]
> When I say it hangs, CTRL-C no longer works...

Okay, weird, maybe it is related to the interrupt handlers after all. Could you try my #52 branch and check if that fixes the problem for you?

> there's the frame of the snap app I was doing it in at https://github.com/GetContented/substance — but that doesn't include hint (that was done as local experimentation on my local machine only) — one could quickly include hint and put a runInterpreter expression in one of the routes

We're going to need a much smaller repro case than that.

**Comment by JulianLeviston** [comment]
@gelisam hey look at that, it works how I'd expect now with your branch ;-) nice! (ie ctrl-c goes back to the prompt in GHCi when I hit ctrl-C). Thanks.

I understand you'd need a smaller repro. I can recommend running `runInterpreter` within the connection handler of a call to `Network.Simple.TCP`. If you need me to build a case, I can.

**Comment by gelisam** [comment]
Great! In that case, it looks like we already have a fix, so we don't need a repro case after all. Closing.
