### ISSUE TITLE
Do not throw exceptions on GHC warnings

### ISSUE THREAD

**Issue by jwaldmann** [mvdan/hint#8]
Source code:
```
$ cat PS.hs 
{-# language PatternSignatures #-}
f (x::Int) = x
main = print (f 0)
```
ghc warns but compiles:
```
$ ghc -fforce-recomp -c PS.hs

PS.hs:1:14: Warning:
    -XPatternSignatures is deprecated: use -XScopedTypeVariables or pragma {-# LANGUAGE ScopedTypeVariables #-} instead
```

hint throws exception:
```
Prelude Language.Haskell.Interpreter> runInterpreter $ do loadModules ["PS.hs" ]
*** Exception: GHC returned a result but said: [GhcError {errMsg = "PS.hs:1:14:\n    -XPatternSignatures is deprecated: use -XScopedTypeVariables or pragma {-# LANGUAGE ScopedTypeVariables #-} instead"}]
```

so, hint treats all warnings as errors? is this configurable?

**Comment by mvdan** [comment]
We seem to be aware that it's not a compiler error - `GHC returned a result but said: ...`

If we don't throw warnings as exceptions, how should we handle them? Should we just ignore them?

**Comment by jwaldmann** [comment]
Maybe this:

1. introduce `hint` option: `handle_warnings :: Ignore | Abort`  or/and
2. change the return type of `runInterpreter` to something like
`Either Error ([Warning],result)`. better, for compatibility, make an extra function that returns more info.

**Comment by mvdan** [comment]
> change the return type of runInterpreter to something like Either Error ([Warning],result)

I'd avoid breaking backwards compatiblity whenever possible, and in this case it seems we have plenty of options.

> introduce hint option: handle_warnings :: Ignore | Abort or/and
> make an extra function that returns more info.

Both of these options represent the same - a way to optionally ignore the errors. I lean towards the first since it's the one that keeps the most consistency with the current approach, while the second could potentially break apps that depend on `hint` excepting on warnings.

**Comment by jwaldmann** [comment]
"ignore errors" => "ignore warnings"?

well, with my second suggestion, you'd get the warning *and* the result, which you cannot
with the first (if you want the result, you don't get to see the warning)

**Comment by mvdan** [comment]
> "ignore errors" => "ignore warnings"?

Yes :)

> well, with my second suggestion, you'd get the warning and the result, which you cannot
with the first (if you want the result, you don't get to see the warning)

You sort of could with the first, by compiling twice. Then again, it wouldn't be easy to gather the warnings themselves.

You've got a point - we should instead keep the warnings around and let the user ask for them if they want to. Warnings should never be exceptions anyway.

**Comment by meditans** [comment]
This issue is the one we talked about here (http://hub.darcs.net/jcpetruzza/hint/issue/7) in the old darcs repo, right?

Following that discussion, should the type of the function

    mayFail :: MonadInterpreter m => m (Maybe a) -> m a

become something like:

    mayFail :: MonadInterpreter m => HandleWarnings -> m (Maybe a) -> m a

Where `data HandleWarnings =  Ignore | Abort`?

Or should we just modify the line:

    (Just _, False) -> fail $ "GHC returned a result but said: " ++ show es

in `Hint.Base.mayFail` to return the actual result?

**Comment by meditans** [comment]
Above is how I solved this particular problem in my local version. I find that semantic satisfying for my purposes: most of the times, I just want to query the code I'm interested in, if it compiles.
Moreover, the signature of `myFail` does not acknowledge explicitly problems with compilations (for which `throw`s an error) neither with other issues (for which it fails). Would a separate function to get warnings be better if a user is interested specifically in warnings?

**Comment by mvdan** [comment]
I do agree with your commit above - warnings should never be thrown as errors. If you open a PR, I'll merge it to fix this bug.

Just a little nit though - keep the `->` indentation.

> Would a separate function to get warnings be better if a user is interested specifically in warnings?

Yes - feel free to open a separate issue about this. I say separate issue because that's a feature rather than a bug. Right now you can sort of get the warnings, but as part of an interpreter error so that doesn't count.
